sudo: required

services:
  - docker

env:
  global:
    DOCKER_FILE=.
    VERSION=$TRAVIS_BRANCH

script:
- echo " --> Selecting the right version"
- if [ $TRAVIS_BRANCH == "master" ]; then
    VERSION="latest";
  fi
- echo " ===> Building image"
- docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$VERSION $DOCKER_FILE
- echo " ===> Image list"
- docker images
- echo " ===> Authentication"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo " ===> Pushing image"
- docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$VERSION

notifications:
  email: false
